# Generated by Django 5.0.6 on 2024-07-23 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('matematica', 'Matemática'), ('lengua', 'Lengua'), ('naturales', 'Ciencias Naturales')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='user',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materias',
            field=models.ManyToManyField(to='aplicacion.materia'),
        ),
    ]
