# Generated by Django 5.0.6 on 2024-07-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_materia_remove_estudiante_biografia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='materias',
            field=models.ManyToManyField(blank=True, to='aplicacion.materia'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(choices=[('matematica', 'Matemática'), ('lengua', 'Lengua'), ('naturales', 'Ciencias Naturales')], max_length=50, unique=True),
        ),
    ]
